const quotes = [
    "Mach dir keine Sorgen, Kaffee steht an deiner Seite ☕😄",
    "Erfolg ist wie Pizza – jeder liebt Pizza! 🍕🚀",
    "Gestern wolltest du das, wofür du heute arbeitest! 💪🌟",
    "Lächeln ist der beste Anzug – trag ihn oft! 😁👔",
    "Verwandle Käse in Selbstvertrauen – du bist gouda genug! 🧀😎",
    "Der Montag ist wie ein Kaltstart – gib Gas! 🚗💨",
    "Schwierigkeiten sind nur Gelegenheiten im Arbeitsanzug! 👔💼",
    "Sei so großartig, dass sie dich 'Käpt'n Fantastisch' nennen! 🦸‍♂️💥",
    "Kämpfe nicht gegen Montage, sie sind auch nur ein Tag! 📅🥊",
    "Du bist ein Einhorn in einer Herde von Eseln! 🦄🐴",
    "Lass uns heute Geschichte schreiben, aber zuerst Kaffee! ☕📜",
    "Denk daran, du rockst! 🎸🤘",
    "Probleme sind nur ungeschminkte Chancen! 💄🌟",
    "Du bist so schlau, dass selbst Google dich sucht! 🧠🔍",
    "Das Ziel ist der Regenbogen, die Arbeit der Topf Gold! 🌈🍯",
    "Arbeit ist wichtig, aber Kuchen auch! 🍰👩‍🍳",
    "Wenn du hinfällst, mach ein Schneengel, bevor du wieder aufstehst! ⛄🆙",
    "Erfolg kommt zu denen, die zuerst Kaffee gießen! ☕💼",
    "Träume groß und arbeite hart – du kannst im Schlaf nicht gewinnen! 💤💪",
    "Sei wie ein Einhorn: Einzigartig und legendär! 🦄🌟",
    "Schlage die Montagsblues mit einem Regenbogen! 🌈🌞",
    "Deine Einstellung beeinflusst deine Höhe – denk groß! 🚀🌄",
    "Jeder Tag ist ein Puzzlestück deines Erfolgs! 🧩🏆",
    "Du bist so heiß, dass selbst der Toast neidisch ist! 🍞🔥",
    "Wenn das Leben Zitronen gibt, mach Limonade draus! 🍋🍹",
    "Erfolg ist kein Zufall, sondern eine Entscheidung! 🎯🚀",
    "Arbeite hart, als ob die Keksdose nie leer wird! 🍪💪",
    "Glaube an dich selbst, du bist der Hauptpreis! 🏆💫",
    "Dein Lächeln ist deine Superkraft – zeig sie allen! 😃💥",
    "Sei so positiv, dass negative Zahlen Angst vor dir haben! ➕😱",
    "Jeder Tag ist eine neue Chance für Kaffee und Erfolg! ☕🌟",
    "Du bist wie Schokolade – immer eine süße Überraschung! 🍫🎉",
    "Montage sind wie Diamanten – selten und wertvoll! 💎💪",
    "Mach die Welt bunter – fang mit deinem Lächeln an! 🌈😁",
    "Arbeite klug, nicht hart – lass die Eule in dir raus! 🦉💡",
    "Lass deine Träume größer sein als deine Sorgen! 💭🌠",
    "Der Weg zum Erfolg ist mit Kaffee gepflastert! ☕🛤️",
    "Gib 100%, es sei denn, du spendest Blut! 💯🩸",
    "Erfolg ist wie ein Haustier – pflege ihn! 🐶🏆",
    "Du bist einzigartig, so wie jeder andere auch! 🤣🤷‍♀️",
    "Lass deine Träume die Schwerkraft überwinden! ✈️🌌",
    "Kaffee: Flüssiges Glück am Morgen! ☕😀",
    "Mit einem Lächeln im Herzen, kannst du alles erreichen! 😄❤️",
    "Lass deine Ideen fliegen wie Einhörner! 🚀🦄",
    "Schokolade ist der Schlüssel zur Weltfrieden! 🍫✌️",
    "Denk daran, du bist der Kapitän deines Lebens! ⚓🚢",
    "Montage sind wie Marshmallows – röste sie und genieße! 🔥👌",
    "Erfolg ist süß wie Honig – arbeite wie eine Biene! 🐝🍯",
    "Du bist ein Meisterwerk in Arbeit – male weiter! 🎨🖌️",
    "Der Weg zum Erfolg ist mit Pausenbrot gepflastert! 🥪🛤️",
    "Träume groß, denn du bist ein Stern im Universum! 🌟🌌",
    "Mit Kaffee in der Hand, kannst du die Welt erobern! ☕🌎",
    "Lass deine Träume fliegen wie Luftballons! 🎈🌈",
    "Schokolade ist Liebe in fester Form! 🍫❤️",
    "Gib dein Bestes und dann gönn dir Kuchen! 🍰🏆",
    "Erfolg ist wie ein Mosaik – Stück für Stück! 🧩🌟",
    "Du bist der Regisseur deines Lebens – Action! 🎬🎥",
    "Montage sind wie Kaffeebohnen – voller Potential! ☕💎",
    "Erfolg ist wie ein Kuchen – teile ihn mit anderen! 🍰👫",
    "Deine Träume sind wie Sterne – greif nach ihnen! 🌟🌠",
    "Mit Kaffee im Blut kannst du Berge versetzen! ☕⛰️",
    "Lächle, es kostet nichts und bringt viel! 😃🌈",
    "Sei so entspannt wie eine Katze in der Sonne! 🐱🌞",
    "Erfolg ist wie ein Selfie – du bist der Star! 📸🌟",
    "Du bist so cool, dass Eis neidisch ist! 🍦❄️",
    "Wenn das Leben dir Zitronen gibt, mach Limonade und lache! 🍋😂",
    "Träume groß, sonst kannst du die Sterne nicht erreichen! 🌌🌠",
    "Mit Kaffee kann jeder ein Superheld sein! ☕💥",
    "Lass deine Träume leuchten wie Glühwürmchen! ✨🌟",
    "Schokolade macht alles besser – probier's aus! 🍫😋",
    "Gib dein Bestes und dann noch ein bisschen mehr! 💪🌟",
    "Erfolg ist wie ein Puzzle – du hast alle Teile! 🧩🏆",
    "Du bist der Regisseur deiner eigenen Komödie! 🎬🤣",
    "Montage sind wie Kekse – knusprig und süß! 🍪👌",
    "Erfolg ist wie ein Tanz – beweg dich und genieße! 💃🕺",
    "Deine Träume sind wie Raketen – zünde sie an! 🚀🌠",
    "Mit Kaffee im Bauch kannst du die Welt umarmen! ☕🌍",
    "Sei so bunt wie ein Regenbogen in einer Schwarzweißwelt! 🌈🌍",
    "Lächeln ist die beste Antwort auf alles! 😊👍",
    "Sei so mutig wie ein Löwe – brüll vor Glück! 🦁📣",
    "Erfolg ist wie ein Eis – genieß ihn, bevor er schmilzt! 🍦🏆",
    "Du bist der Kapitän deines Lebensschiffs – steuer es! ⚓🚢",
    "Montage sind wie Schatzsuchen – finde den Spaß! 💰😄",
    "Erfolg ist wie ein Sprung ins Wasser – erfrischend! 🏊‍♂️💦",
    "Deine Träume sind wie Seifenblasen – lass sie fliegen! 🎈🌟",
    "Mit Kaffee im Herzen bist du unbesiegbar! ☕❤️",
    "Lass deine Gedanken wie Konfetti regnen! 🎉🎊",
    "Erfolg ist wie ein Witz – lache darüber! 😂🌟",
    "Du bist so süß wie Zuckerwatte! 🍭😁",
    "Montage sind wie Startschüsse – sei der Gewinner! 🏁🏆",
    "Erfolg ist wie ein Abenteuer – geh raus und erlebe es! 🌍🌟",
    "Deine Träume sind wie Bücher – schreib deine Geschichte! 📚📝",
    "Mit Kaffee im Blut bist du der Held des Tages! ☕🦸‍♂️",
    "Lass deine Ideen wie Ballons steigen! 🎈🌟",
    "Erfolg ist wie ein Cocktail – mixe ihn nach deinem Geschmack! 🍹🏆",
    "Du bist der CEO deines Lebens – führe es klug! 👔💼",
    "Montage sind wie Sonnenaufgänge – voller Möglichkeiten! 🌅🌟",
    "Erfolg ist wie ein Kuchen – teile ihn großzügig! 🍰🤝",
    "Deine Träume sind wie Sterne – folge ihrem Licht! 🌟🌌",
    "Mit Kaffee im Tank fährst du auf der Überholspur des Lebens! ☕🚗"
]

function newQuote() {
    let randomNumber = Math.floor(Math.random()* (quotes.length));
    document.querySelector('.motivation-container').innerHTML = `
    <div class="counter-motivation">    
    <p class="motivation-quote">${quotes[randomNumber]}</p>
    </div>`;
}

export {quotes, newQuote};
